// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2-r9pjW8EcyWBsBlVw3NPJB6C5Xgugz8',
    appId: '1:287769394046:web:d8a84bfb241adc1613912f',
    messagingSenderId: '287769394046',
    projectId: 'pets-app-292ab',
    authDomain: 'pets-app-292ab.firebaseapp.com',
    storageBucket: 'pets-app-292ab.firebasestorage.app',
    measurementId: 'G-T1JNYMFCL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChLyLKeGN2MfIUK0S-sccFGCfDY7E2rv8',
    appId: '1:287769394046:android:d79388a2ee8914a813912f',
    messagingSenderId: '287769394046',
    projectId: 'pets-app-292ab',
    storageBucket: 'pets-app-292ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_2TRt_VBWkLaMiF-1uONWXRpQ9jo4gXA',
    appId: '1:287769394046:ios:b5051e763e69ceb413912f',
    messagingSenderId: '287769394046',
    projectId: 'pets-app-292ab',
    storageBucket: 'pets-app-292ab.firebasestorage.app',
    iosBundleId: 'mnk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_2TRt_VBWkLaMiF-1uONWXRpQ9jo4gXA',
    appId: '1:287769394046:ios:b5051e763e69ceb413912f',
    messagingSenderId: '287769394046',
    projectId: 'pets-app-292ab',
    storageBucket: 'pets-app-292ab.firebasestorage.app',
    iosBundleId: 'mnk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2-r9pjW8EcyWBsBlVw3NPJB6C5Xgugz8',
    appId: '1:287769394046:web:7e80309ed4c1cdaa13912f',
    messagingSenderId: '287769394046',
    projectId: 'pets-app-292ab',
    authDomain: 'pets-app-292ab.firebaseapp.com',
    storageBucket: 'pets-app-292ab.firebasestorage.app',
    measurementId: 'G-0WLESTP7GP',
  );
}
